version: "3.9"
services:
  db:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_DB: mobiles_data_db
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  api:
    build: ./api/api4G
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api/api4G:/app
    environment:
      DJANGO_SECRET_KEY: dev
      DJANGO_DEBUG: "True"
      DATABASE_URL: postgres://devuser:devpass@db:5432/devdb
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./front
    command: npm start -- --host 0.0.0.0 --port 4200
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - api

volumes:
  dbdata: