# Generated by Django 5.2.6 on 2025-09-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=20)),
                ('long', models.FloatField(default=0)),
                ('lat', models.FloatField(default=0)),
                ('is_2g', models.BooleanField()),
                ('is_3g', models.BooleanField()),
                ('is_4g', models.BooleanField()),
            ],
        ),
    ]
